### PR TITLE
10.0 [1691][FIX] mail_compose_message_reply_to;add_depends_into_manifest_py

### PR DESCRIPTION
**Pull request by tack-yabeQuartile**
[1691](https://www.quartile.co/web#id=1691&model=project.task&view_type=form&menu_id=)

from staging PR
#73

### CODE REVIEW

**Comment by tack-yabeQuartile** [comment]
Travis Error is the usually one. (see #66,#72,#73)

**Review by yostashiro — APPROVED** [review]
👍

**Comment by tack-yabeQuartile** [comment]
Merged, but not reflected to the server. I cannot access MI7 production server .......

**Comment by yostashiro** [comment]
> Merged, but not reflected to the server. I cannot access MI7 production server .......

@tack-yabeQuartile Let me take care of it now.

**Pull request merged**
