### PR TITLE
st1 [1691][ADD] sale_automatic_workflow_propose

### PR DESCRIPTION
**Pull request by yostashiro**
[1691](https://www.quartile.co/web?debug=1#id=1691&action=771&model=project.task&view_type=form&menu_id=505)

### CODE REVIEW

**Comment by TimLai125** [comment]
@yostashiro I guess the following logic needs to be adjusted as well?
https://github.com/qrtl/pro_mi7-temp/blob/a7f7ddafe446291caeefa1c4de866eb40d9499de/pro_mi7_website_sale_ec/models/sale_order.py#L158-L171

**Comment by yostashiro** [comment]
@TimLai125 Thanks for the comment. No, it actually doesn't for now. This module itself is (on purpose) made to handle B2C cases as well depending on the configuration, but in reality the function of the module is expected to be used for B2B only for the time being.

It certainly is an idea to deprecate the part you quote and start using the automatic workflow for B2C in the future, though. We just don't want to touch the part that's been working at this point.

**Review by TimLai125 — APPROVED** [review]
LGTM

**Comment by yostashiro** [comment]
There will be a merge conflict moving this to the 10.0 branch on oca_dependencies.txt due to this https://github.com/qrtl/mi7-custom/pull/33.

**Pull request merged**
