### PR TITLE
15st1 [2874][ADD] product_resize_for_applying_zoom_in

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
[2874](https://www.quartile.co/web#id=2874&action=771&model=project.task&view_type=form&menu_id=505)

### CODE REVIEW

**Comment by yostashiro** [comment]
@AungKoKoLin1997 With a quick look I am not totally convinced that this should be the design to go.  Can you please explain first how you concluded with this design with links to relevant parts of the Odoo code?

**Comment by AungKoKoLin1997** [comment]
> @AungKoKoLin1997 With a quick look I am not totally convinced that this should be the design to go. Can you please explain first how you concluded with this design with links to relevant parts of the Odoo code?

My plan is to apply the image size for zoom-in feature. Odoo zoom-in feature support for above 1024 px. So, my idea is if the user upload the image less than this size, automatically resize the image that are enough for zoom-in feature.

**Comment by yostashiro** [comment]
@AungKoKoLin1997 As mentioned yesterday in our conversation, I'd like to know how you made the design decision out of all options (the reason).  Not necessarily what you are doing because I can tell that from the code.

**Comment by yostashiro** [comment]
Closing this as the solution seems to be invalid (even if the client needs custom development).

**Pull request closed without merging**
