### PR TITLE
15st1 [2431][UPD] update dotfiles

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
[2431](https://www.quartile.co/web#id=2431&action=771&model=project.task&view_type=form&menu_id=505)

### CODE REVIEW

**Comment by yostashiro** [comment]
@AungKoKoLin1997 Please do not ignore the CI error.  When you see an error, please first check if you you can solve it.  If you cannot, then report the issue and ask for advice.  Do not just ignore the error and request a review.

Edit: I think I told you not to worry about the pre-commit/CI error when dotfiles are added, so maybe you just did according to what I said. To add context to my above comment, the CI error this time was coming from not being able to install the dependencies, which in my view is within the scope of the dotfile preparation.

**Comment by yostashiro** [comment]
```
ERROR: Could not find a version that satisfies the requirement odoo-addon-website_sale_delivery_date<15.1dev,>=15.0dev (from versions: none)
ERROR: No matching distribution found for odoo-addon-website_sale_delivery_date<15.1dev,>=15.0dev
Error: Process completed with exit code 1.
```

This CI error indicates that we should move website_sale_delivery_date module (or at least the relevant part of it) to mi7-custom.  We will later sort this out separately.

**Comment by AungKoKoLin1997** [comment]
> Please do not ignore the CI error. When you see an error, please first check if you you can solve it. If you cannot, then report the issue and ask for advice. Do not just ignore the error and request a review.

Yes. As you mentioned , I thought that is the pre-commit error and I decided we will fix this with another PR that fix pre-commit issues and undetected dependencies.

**Comment by AungKoKoLin1997** [comment]
> This CI error indicates that we should move website_sale_delivery_date module (or at least the relevant part of it) to mi7-custom. We will later sort this out separately.

Should I create PR for moving "website_sale_delivery_date" module from mi7-private to mi7-custom?

**Comment by yostashiro** [comment]
@AungKoKoLin1997 Thanks for your attention. See [2856](https://www.quartile.co/web?debug=1#id=2856&action=771&model=project.task&view_type=form&menu_id=505).

**Pull request merged**
